language: go
go:
  - 1.2
  - tip

install:
  - go get -v -d ./...
  - go get -v github.com/onsi/ginkgo
  - go get -v github.com/onsi/gomega
  - go install -v github.com/onsi/ginkgo/ginkgo

script: PATH=$GOPATH/bin:$PATH; ginkgo -r -i --randomizeAllSpecs --failOnPending --skipMeasurements --cover